services:
  - type: web
    name: python-mtprotoproxy
    env: python
    plan: free
    buildCommand: ""
    startCommand: "bash start.sh"
    envVars:
      - key: SECRET
        sync: false
      - key: PORT
        value: "443"
